package com.zrq.entity;

import java.util.Date;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_ch_name
     *
     * @mbggenerated
     */
    private String brandChName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_abbr_name
     *
     * @mbggenerated
     */
    private String brandAbbrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_id
     *
     * @return the value of brand.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_id
     *
     * @param brandId the value for brand.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_name
     *
     * @return the value of brand.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_name
     *
     * @param brandName the value for brand.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_ch_name
     *
     * @return the value of brand.brand_ch_name
     *
     * @mbggenerated
     */
    public String getBrandChName() {
        return brandChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_ch_name
     *
     * @param brandChName the value for brand.brand_ch_name
     *
     * @mbggenerated
     */
    public void setBrandChName(String brandChName) {
        this.brandChName = brandChName == null ? null : brandChName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_abbr_name
     *
     * @return the value of brand.brand_abbr_name
     *
     * @mbggenerated
     */
    public String getBrandAbbrName() {
        return brandAbbrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_abbr_name
     *
     * @param brandAbbrName the value for brand.brand_abbr_name
     *
     * @mbggenerated
     */
    public void setBrandAbbrName(String brandAbbrName) {
        this.brandAbbrName = brandAbbrName == null ? null : brandAbbrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.create_time
     *
     * @return the value of brand.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.create_time
     *
     * @param createTime the value for brand.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.update_time
     *
     * @return the value of brand.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.update_time
     *
     * @param updateTime the value for brand.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}