package com.zrq.entity;

public class TagDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_dict.tag_id
     *
     * @mbggenerated
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_dict.tag_code
     *
     * @mbggenerated
     */
    private String tagCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_dict.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_dict.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_dict.tag_ch_name
     *
     * @mbggenerated
     */
    private String tagChName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_dict.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_dict.tag_id
     *
     * @return the value of tag_dict.tag_id
     *
     * @mbggenerated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_dict.tag_id
     *
     * @param tagId the value for tag_dict.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_dict.tag_code
     *
     * @return the value of tag_dict.tag_code
     *
     * @mbggenerated
     */
    public String getTagCode() {
        return tagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_dict.tag_code
     *
     * @param tagCode the value for tag_dict.tag_code
     *
     * @mbggenerated
     */
    public void setTagCode(String tagCode) {
        this.tagCode = tagCode == null ? null : tagCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_dict.tag_name
     *
     * @return the value of tag_dict.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_dict.tag_name
     *
     * @param tagName the value for tag_dict.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_dict.brand_name
     *
     * @return the value of tag_dict.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_dict.brand_name
     *
     * @param brandName the value for tag_dict.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_dict.tag_ch_name
     *
     * @return the value of tag_dict.tag_ch_name
     *
     * @mbggenerated
     */
    public String getTagChName() {
        return tagChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_dict.tag_ch_name
     *
     * @param tagChName the value for tag_dict.tag_ch_name
     *
     * @mbggenerated
     */
    public void setTagChName(String tagChName) {
        this.tagChName = tagChName == null ? null : tagChName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_dict.brand_id
     *
     * @return the value of tag_dict.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_dict.brand_id
     *
     * @param brandId the value for tag_dict.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
}